"""empty message

Revision ID: 14b7ad80462
Revises: 1622940ca6d
Create Date: 2015-04-13 19:12:03.092742

"""

# revision identifiers, used by Alembic.
revision = '14b7ad80462'
down_revision = '1622940ca6d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
