"""empty message

Revision ID: 14cca4fb682
Revises: 499c66f03c0
Create Date: 2015-04-16 19:49:57.328663

"""

# revision identifiers, used by Alembic.
revision = '14cca4fb682'
down_revision = '499c66f03c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
