"""empty message

Revision ID: 1622940ca6d
Revises: 2511f10f73f
Create Date: 2015-04-13 19:11:46.833032

"""

# revision identifiers, used by Alembic.
revision = '1622940ca6d'
down_revision = '2511f10f73f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
