"""empty message

Revision ID: 1cfe8c4a00e
Revises: 796de1da12
Create Date: 2015-04-16 14:44:51.069004

"""

# revision identifiers, used by Alembic.
revision = '1cfe8c4a00e'
down_revision = '796de1da12'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=128), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('product_type', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_manufacturer'), 'models', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_models_model_name'), 'models', ['model_name'], unique=False)
    op.create_table('skus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_product_id', sa.Integer(), nullable=True),
    sa.Column('stock_code', sa.String(length=255), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['base_product_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skus_stock_code'), 'skus', ['stock_code'], unique=True)
    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('segmentation', sa.String(length=64), nullable=True),
    sa.Column('market', sa.String(length=10), nullable=True),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('old_price', sa.Float(), nullable=True),
    sa.Column('abo_price', sa.Float(), nullable=True),
    sa.Column('offer_url', sa.String(length=255), nullable=True),
    sa.Column('tariff_plan_code', sa.String(length=16), nullable=True),
    sa.Column('offer_code', sa.String(length=16), nullable=True),
    sa.Column('contract_condition_code', sa.String(length=3), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_url')
    )
    op.create_index(op.f('ix_offers_category'), 'offers', ['category'], unique=False)
    op.create_index(op.f('ix_offers_contract_condition_code'), 'offers', ['contract_condition_code'], unique=False)
    op.create_index(op.f('ix_offers_offer_code'), 'offers', ['offer_code'], unique=False)
    op.create_index(op.f('ix_offers_tariff_plan_code'), 'offers', ['tariff_plan_code'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['sku_id'], ['skus.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_photos_default'), 'photos', ['default'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_default'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_offers_tariff_plan_code'), table_name='offers')
    op.drop_index(op.f('ix_offers_offer_code'), table_name='offers')
    op.drop_index(op.f('ix_offers_contract_condition_code'), table_name='offers')
    op.drop_index(op.f('ix_offers_category'), table_name='offers')
    op.drop_table('offers')
    op.drop_index(op.f('ix_skus_stock_code'), table_name='skus')
    op.drop_table('skus')
    op.drop_index(op.f('ix_models_model_name'), table_name='models')
    op.drop_index(op.f('ix_models_manufacturer'), table_name='models')
    op.drop_table('models')
    ### end Alembic commands ###
