"""empty message

Revision ID: 1d68a94e98d
Revises: 14b7ad80462
Create Date: 2015-04-13 20:47:41.662807

"""

# revision identifiers, used by Alembic.
revision = '1d68a94e98d'
down_revision = '14b7ad80462'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models', 'priority')
    op.add_column('offers', sa.Column('priority', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'priority')
    op.add_column('models', sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
