"""empty message

Revision ID: 2511f10f73f
Revises: 382853f7674
Create Date: 2015-04-13 19:11:22.518475

"""

# revision identifiers, used by Alembic.
revision = '2511f10f73f'
down_revision = '382853f7674'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
