"""empty message

Revision ID: 3184968d292
Revises: 9df71e2d23
Create Date: 2015-04-13 18:41:47.219401

"""

# revision identifiers, used by Alembic.
revision = '3184968d292'
down_revision = '9df71e2d23'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('default', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_photos_default'), 'photos', ['default'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_default'), table_name='photos')
    op.drop_column('photos', 'default')
    ### end Alembic commands ###
