"""empty message

Revision ID: 6a6d422a81
Revises: None
Create Date: 2015-04-11 13:16:13.240518

"""

# revision identifiers, used by Alembic.
revision = '6a6d422a81'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(length=128), nullable=True),
    sa.Column('model_name', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('product_type', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_models_manufacturer'), 'models', ['manufacturer'], unique=False)
    op.create_index(op.f('ix_models_model_name'), 'models', ['model_name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_models_model_name'), table_name='models')
    op.drop_index(op.f('ix_models_manufacturer'), table_name='models')
    op.drop_table('models')
    ### end Alembic commands ###
