"""empty message

Revision ID: 9df71e2d23
Revises: 3bbfab4668
Create Date: 2015-04-13 14:07:49.368900

"""

# revision identifiers, used by Alembic.
revision = '9df71e2d23'
down_revision = '3bbfab4668'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offers', sa.Column('abo_price', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offers', 'abo_price')
    ### end Alembic commands ###
